version: '3.5'

services:
  proxyreverse:
    image: nginx:alpine
    restart: always
#    env_file: ./.env
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - app 
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs/mycompany.crt:/etc/ssl/certs/myca.crt
      - ./certs/mycompany.key:/etc/ssl/private/myprivate.key
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
